version: "3.3"
services:
  muce-api:
    image: muceapi:latest
    container_name: "muce-api"
    restart: "unless-stopped"
    ports:
      - "8080:8080"
    volumes:
      - "./muce-api/config.yml:/opt/muce/config.yml"
      - "./data:/opt/muce/data"
      - "/var/run/docker.sock:/var/run/docker.sock"

  traefik:
    image: "traefik:v2.2"
    container_name: "muce-traefik"
    restart: unless-stopped
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:8081"
      - "--accesslog=true"
      - "--accesslog.filepath=/srv/docker/traefik/access.log"
      - "--serverstransport.insecureskipverify=true"
    ports:
      - "8081:8081"
      - "8082:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik:/srv/docker/traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.muce-traefik.rule=PathPrefix(`/traefik`) || PathPrefix(`/dashboard`) || PathPrefix(`/api`)"
      - "traefik.http.routers.muce-traefik.entrypoints=web"
      - "traefik.http.services.muce-traefik.loadbalancer.server.port=8080"
      - "traefik.docker.network=muce-traefik"
    networks:
      - muce-traefik
  
  php:
    image: php:fpm
    container_name: "muce-php-fpm"
    restart: unless-stopped
    networks:
      - nginx-net
    volumes:
     - "./data:/var/www"

  nginx:
    image: nginx
    container_name: "muce-nginx"
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - "./data:/var/www"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.muce-nginx.rule=PathPrefix(`/preview`)"
      - "traefik.http.middlewares.muce-nginx-replacepathregex.replacepathregex.regex=\/preview\/(\\d*)\/?"
      - "traefik.http.middlewares.muce-nginx-replacepathregex.replacepathregex.replacement=/$${1}/config/"
      - "traefik.http.routers.muce-nginx.middlewares=muce-nginx-replacepathregex"
      - "traefik.http.routers.muce-nginx.entrypoints=web"
      - "traefik.http.services.muce-nginx.loadbalancer.server.port=80"
      - "traefik.docker.network=muce-traefik"
    networks:
      - muce-traefik
      - nginx-net

networks:
  muce-traefik:
    external: true
  nginx-net:
    driver: bridge
